# Generated by Django 2.1 on 2020-04-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offert',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
